---
- name: Ping hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Display ping results
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is reachable"
